project_id = "ftbkgssklyrtkqttbkyn"

[functions.consulta-intimacoes]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.executar-consultas-agendadas]
verify_jwt = false

[functions.baixar-caderno]
verify_jwt = false
